---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stories/api.storiesfromtheweb.org/

    # Clean out the target directory (preserving .well-known)
    - /bin/rm -rf $DEPLOYPATH/* || true
    - find $DEPLOYPATH -mindepth 1 -maxdepth 1 -name ".*" ! -name "." ! -name ".." ! -name ".well-known" -exec /bin/rm -rf {} \; || true

    # Create base directories
    - /bin/mkdir -p $DEPLOYPATH/api/v1/Core
    - /bin/mkdir -p $DEPLOYPATH/admin

    # Copy API structure
    - /bin/cp -R stories-backend/api/* $DEPLOYPATH/api/
    - /bin/cp -R stories-backend/api/.htaccess $DEPLOYPATH/api/
    - /bin/cp -R stories-backend/api/v1/* $DEPLOYPATH/api/v1/

    # Copy admin structure
    - /bin/cp -R stories-backend/admin/* $DEPLOYPATH/admin/
    - /bin/cp -R stories-backend/admin/.htaccess $DEPLOYPATH/admin/

    # Copy root files
    - /bin/cp stories-backend/*.php $DEPLOYPATH/
    - /bin/cp stories-backend/.htaccess $DEPLOYPATH/
    - /bin/cp stories-backend/database.sql $DEPLOYPATH/
    - /bin/cp stories-backend/README.md $DEPLOYPATH/

    # Set core permissions
    - /bin/chmod 755 $DEPLOYPATH/api/v1/Core
    - /bin/chmod 644 $DEPLOYPATH/api/v1/Core/*.php

    # Set admin permissions
    - /bin/chmod 755 $DEPLOYPATH/admin/uploads
    - /bin/find $DEPLOYPATH/admin -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH/admin -type f -exec /bin/chmod 644 {} \;
