---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stories/api.storiesfromtheweb.org/
    - export SOURCEPATH=/home/stories/repositories/stories/stories-backend/

    # Clean out the target directory (preserving .well-known)
    - /bin/rm -rf $DEPLOYPATH/* || true
    - find $DEPLOYPATH -mindepth 1 -maxdepth 1 -name ".*" ! -name "." ! -name ".." ! -name ".well-known" -exec /bin/rm -rf {} \; || true

    # Create necessary directories
    - /bin/mkdir -p $DEPLOYPATH/api/v1/Core
    - /bin/mkdir -p $DEPLOYPATH/admin

    # Copy root level files
    - /bin/cp $SOURCEPATH/*.php $DEPLOYPATH/
    - /bin/cp $SOURCEPATH/.htaccess $DEPLOYPATH/
    - /bin/cp $SOURCEPATH/database.sql $DEPLOYPATH/
    - /bin/cp $SOURCEPATH/README.md $DEPLOYPATH/

    # Handle Core files first (case-sensitive)
    - /bin/cp $SOURCEPATH/api/v1/Core/Auth.php $DEPLOYPATH/api/v1/Core/
    - /bin/cp $SOURCEPATH/api/v1/Core/ClassLoader.php $DEPLOYPATH/api/v1/Core/
    - /bin/cp $SOURCEPATH/api/v1/Core/Router.php $DEPLOYPATH/api/v1/Core/
    - /bin/cp $SOURCEPATH/api/v1/Core/BaseController.php $DEPLOYPATH/api/v1/Core/
    - /bin/cp $SOURCEPATH/api/v1/Core/Database.php $DEPLOYPATH/api/v1/Core/

    # Copy API files
    - find $SOURCEPATH/api -type f -name "*.php" ! -path "*/v1/Core/*" -exec /bin/cp {} $DEPLOYPATH/api/ \;
    - /bin/cp $SOURCEPATH/api/.htaccess $DEPLOYPATH/api/

    # Copy admin structure
    - /bin/cp -R $SOURCEPATH/admin/* $DEPLOYPATH/admin/
    - /bin/cp $SOURCEPATH/admin/.htaccess $DEPLOYPATH/admin/

    # Set permissions
    - /bin/chmod 755 $DEPLOYPATH/api/v1/Core
    - /bin/chmod 644 $DEPLOYPATH/api/v1/Core/*.php
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;
    - /bin/chmod 775 $DEPLOYPATH/admin/uploads
