---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stories/api.storiesfromtheweb.org/

    # Clean out the target directory (preserving .well-known)
    - /bin/rm -rf $DEPLOYPATH/* || true
    - find $DEPLOYPATH -mindepth 1 -maxdepth 1 -name ".*" ! -name "." ! -name ".." ! -name ".well-known" -exec /bin/rm -rf {} \; || true

    # Create base directories first
    - /bin/mkdir -p $DEPLOYPATH/api
    - /bin/mkdir -p $DEPLOYPATH/admin
    
    # Create API directory structure
    - /bin/mkdir -p $DEPLOYPATH/api/v1/Core
    - /bin/mkdir -p $DEPLOYPATH/api/v1/Endpoints
    - /bin/mkdir -p $DEPLOYPATH/api/v1/middleware
    - /bin/mkdir -p $DEPLOYPATH/api/v1/Utils
    - /bin/mkdir -p $DEPLOYPATH/api/v1/config
    
    # Create admin directory structure
    - /bin/mkdir -p $DEPLOYPATH/admin/views/auth
    - /bin/mkdir -p $DEPLOYPATH/admin/views/generic
    - /bin/mkdir -p $DEPLOYPATH/admin/views/layouts
    - /bin/mkdir -p $DEPLOYPATH/admin/includes
    - /bin/mkdir -p $DEPLOYPATH/admin/assets/css
    - /bin/mkdir -p $DEPLOYPATH/admin/assets/js
    - /bin/mkdir -p $DEPLOYPATH/admin/assets/img
    - /bin/mkdir -p $DEPLOYPATH/admin/controllers
    - /bin/mkdir -p $DEPLOYPATH/admin/uploads
    
    # Set initial directory permissions
    - /bin/chmod 755 $DEPLOYPATH/api
    - /bin/chmod 755 $DEPLOYPATH/admin
    - /bin/chmod 755 $DEPLOYPATH/admin/views
    - /bin/chmod 755 $DEPLOYPATH/admin/includes
    - /bin/chmod 755 $DEPLOYPATH/admin/assets
    - /bin/chmod 755 $DEPLOYPATH/admin/controllers
    - /bin/chmod 755 $DEPLOYPATH/admin/uploads
    
    # Copy API files
    - /bin/cp stories-backend/api/.htaccess $DEPLOYPATH/api/
    - /bin/cp stories-backend/api/*.php $DEPLOYPATH/api/
    
    # Copy core files with proper case
    - /bin/cp stories-backend/api/v1/Core/Auth.php $DEPLOYPATH/api/v1/Core/
    - /bin/cp stories-backend/api/v1/Core/ClassLoader.php $DEPLOYPATH/api/v1/Core/
    - /bin/cp stories-backend/api/v1/Core/Router.php $DEPLOYPATH/api/v1/Core/
    - /bin/cp stories-backend/api/v1/Core/BaseController.php $DEPLOYPATH/api/v1/Core/
    - /bin/cp stories-backend/api/v1/Core/Database.php $DEPLOYPATH/api/v1/Core/
    
    # Copy API structure
    - /bin/cp -R stories-backend/api/v1/config/* $DEPLOYPATH/api/v1/config/
    - /bin/cp -R stories-backend/api/v1/Endpoints/* $DEPLOYPATH/api/v1/Endpoints/
    - /bin/cp -R stories-backend/api/v1/middleware/* $DEPLOYPATH/api/v1/middleware/
    - /bin/cp -R stories-backend/api/v1/Utils/* $DEPLOYPATH/api/v1/Utils/
    
    # Copy admin files
    - /bin/cp stories-backend/admin/.htaccess $DEPLOYPATH/admin/
    - /bin/cp stories-backend/admin/*.php $DEPLOYPATH/admin/
    - /bin/cp -R stories-backend/admin/views/auth/* $DEPLOYPATH/admin/views/auth/
    - /bin/cp -R stories-backend/admin/views/generic/* $DEPLOYPATH/admin/views/generic/
    - /bin/cp -R stories-backend/admin/views/layouts/* $DEPLOYPATH/admin/views/layouts/
    - /bin/cp -R stories-backend/admin/includes/* $DEPLOYPATH/admin/includes/
    - /bin/cp -R stories-backend/admin/assets/css/* $DEPLOYPATH/admin/assets/css/
    - /bin/cp -R stories-backend/admin/assets/js/* $DEPLOYPATH/admin/assets/js/
    - /bin/cp -R stories-backend/admin/assets/img/* $DEPLOYPATH/admin/assets/img/
    - /bin/cp -R stories-backend/admin/controllers/* $DEPLOYPATH/admin/controllers/
    
    # Copy root level files
    - /bin/cp stories-backend/check_auth_status.php $DEPLOYPATH
    - /bin/cp stories-backend/direct_login.php $DEPLOYPATH
    - /bin/cp stories-backend/go_to_dashboard.php $DEPLOYPATH
    - /bin/cp stories-backend/logout.php $DEPLOYPATH
    - /bin/cp stories-backend/.htaccess $DEPLOYPATH
    - /bin/cp stories-backend/database.sql $DEPLOYPATH
    - /bin/cp stories-backend/README.md $DEPLOYPATH
    
    # Set final permissions
    - /bin/chmod 644 $DEPLOYPATH/api/v1/Core/*.php
    - /bin/chmod 644 $DEPLOYPATH/api/v1/Endpoints/*.php
    - /bin/chmod 644 $DEPLOYPATH/api/v1/middleware/*.php
    - /bin/chmod 644 $DEPLOYPATH/api/v1/Utils/*.php
    - /bin/chmod 644 $DEPLOYPATH/api/v1/config/*.php
    - /bin/chmod 644 $DEPLOYPATH/api/*.php
    - /bin/chmod 644 $DEPLOYPATH/api/.htaccess
    - /bin/chmod 644 $DEPLOYPATH/admin/*.php
    - /bin/chmod 644 $DEPLOYPATH/admin/.htaccess
    - /bin/chmod 644 $DEPLOYPATH/admin/views/*/*.php
    - /bin/chmod 644 $DEPLOYPATH/admin/includes/*.php
    - /bin/chmod 644 $DEPLOYPATH/admin/assets/css/*.css
    - /bin/chmod 644 $DEPLOYPATH/admin/assets/js/*.js
    - /bin/chmod 644 $DEPLOYPATH/admin/controllers/*.php
    - /bin/chmod 644 $DEPLOYPATH/*.php
    - /bin/chmod 644 $DEPLOYPATH/.htaccess
    - /bin/chmod 775 $DEPLOYPATH/admin/uploads
