---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stories/api.storiesfromtheweb.org/

    # Clean out the target directory
    - /bin/rm -rf $DEPLOYPATH/* || true
    - find $DEPLOYPATH -mindepth 1 -maxdepth 1 -name ".*" ! -name "." ! -name ".." ! -name ".well-known" -exec /bin/rm -rf {} \; || true

    # Create core directories with proper case
    - /bin/mkdir -p $DEPLOYPATH/api/v1/Core
    
    # Copy core files with proper case
    - /bin/cp stories-backend/api/v1/Core/Auth.php $DEPLOYPATH/api/v1/Core/
    - /bin/cp stories-backend/api/v1/Core/ClassLoader.php $DEPLOYPATH/api/v1/Core/
    - /bin/cp stories-backend/api/v1/Core/Router.php $DEPLOYPATH/api/v1/Core/
    - /bin/cp stories-backend/api/v1/Core/BaseController.php $DEPLOYPATH/api/v1/Core/
    - /bin/cp stories-backend/api/v1/Core/Database.php $DEPLOYPATH/api/v1/Core/
    
    # Copy remaining files/folders
    - /bin/cp -R stories-backend/api/v1/config $DEPLOYPATH/api/v1/
    - /bin/cp -R stories-backend/api/v1/Endpoints $DEPLOYPATH/api/v1/
    - /bin/cp -R stories-backend/api/v1/middleware $DEPLOYPATH/api/v1/
    - /bin/cp -R stories-backend/api/v1/Utils $DEPLOYPATH/api/v1/
    
    # Copy API root files
    - /bin/cp stories-backend/api/*.php $DEPLOYPATH/api/

    # Copy dotfiles from stories-backend (e.g. .htaccess), excluding .git
    - find stories-backend -maxdepth 1 -name ".*" ! -name "." ! -name ".." ! -name ".git" -exec /bin/cp -R {} $DEPLOYPATH \;
