---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stories/api.storiesfromtheweb.org/

    # Clean out the target directory (preserving .well-known)
    - /bin/rm -rf $DEPLOYPATH/* || true
    - find $DEPLOYPATH -mindepth 1 -maxdepth 1 -name ".*" ! -name "." ! -name ".." ! -name ".well-known" -exec /bin/rm -rf {} \; || true

    # Copy root files first
    - /bin/cp stories-backend/*.php $DEPLOYPATH/
    - /bin/cp stories-backend/.htaccess $DEPLOYPATH/
    - /bin/cp stories-backend/database.sql $DEPLOYPATH/
    - /bin/cp stories-backend/README.md $DEPLOYPATH/

    # Handle API structure
    - /bin/mkdir -p $DEPLOYPATH/api/v1/Core
    - /bin/cp stories-backend/api/.htaccess $DEPLOYPATH/api/
    - /bin/cp stories-backend/api/*.php $DEPLOYPATH/api/
    
    # Copy Core files explicitly to maintain case
    - /bin/cp stories-backend/api/v1/Core/*.php $DEPLOYPATH/api/v1/Core/
    
    # Copy remaining API directories
    - /bin/cp -R stories-backend/api/v1/config $DEPLOYPATH/api/v1/
    - /bin/cp -R stories-backend/api/v1/Endpoints $DEPLOYPATH/api/v1/
    - /bin/cp -R stories-backend/api/v1/middleware $DEPLOYPATH/api/v1/
    - /bin/cp -R stories-backend/api/v1/Utils $DEPLOYPATH/api/v1/

    # Handle admin structure
    - /bin/cp -R stories-backend/admin $DEPLOYPATH/
    - /bin/cp stories-backend/admin/.htaccess $DEPLOYPATH/admin/

    # Set core permissions
    - /bin/chmod 755 $DEPLOYPATH/api/v1/Core
    - /bin/chmod 644 $DEPLOYPATH/api/v1/Core/*.php

    # Set admin permissions
    - /bin/chmod 755 $DEPLOYPATH/admin/uploads
    - /bin/find $DEPLOYPATH/admin -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH/admin -type f -exec /bin/chmod 644 {} \;
