---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stories/api.storiesfromtheweb.org/

    # Clean out the target directory
    - /bin/rm -rf $DEPLOYPATH/* || true
    - find $DEPLOYPATH -mindepth 1 -maxdepth 1 -name ".*" ! -name "." ! -name ".." ! -name ".well-known" -exec /bin/rm -rf {} \; || true

    # Copy all normal files/folders from stories-backend/
    - /bin/cp -R stories-backend/* $DEPLOYPATH

    # Copy dotfiles from stories-backend (e.g. .htaccess), excluding .git
    - find stories-backend -maxdepth 1 -name ".*" ! -name "." ! -name ".." ! -name ".git" -exec /bin/cp -R {} $DEPLOYPATH \;
