---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stories/api.storiesfromtheweb.org/

    # Create base directories
    - /bin/mkdir -p $DEPLOYPATH/admin
    - /bin/mkdir -p $DEPLOYPATH/api

    # Copy admin structure first
    - /bin/cp -R stories-backend/admin/assets $DEPLOYPATH/admin/
    - /bin/cp -R stories-backend/admin/includes $DEPLOYPATH/admin/
    - /bin/cp -R stories-backend/admin/views $DEPLOYPATH/admin/
    - /bin/cp -R stories-backend/admin/controllers $DEPLOYPATH/admin/
    - /bin/cp stories-backend/admin/*.php $DEPLOYPATH/admin/
    - /bin/cp stories-backend/admin/.htaccess $DEPLOYPATH/admin/

    # Set admin permissions
    - /bin/chmod -R 755 $DEPLOYPATH/admin
    - /bin/find $DEPLOYPATH/admin -type f -exec /bin/chmod 644 {} \;
    - /bin/chmod 775 $DEPLOYPATH/admin/uploads

    # Copy root files
    - /bin/cp stories-backend/*.php $DEPLOYPATH/
    - /bin/cp stories-backend/.htaccess $DEPLOYPATH/
    - /bin/chmod 644 $DEPLOYPATH/*.php
    - /bin/chmod 644 $DEPLOYPATH/.htaccess
