[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  STRAPI_URL = ""  # Empty string will cause fetchFromStrapi to fail gracefully and fall back to mock data

# Removed functions directory setting

# Removed redirects to non-existent functions

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"