[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  PUBLIC_API_URL = "https://api.storiesfromtheweb.org/api/v1"

[context.production.environment]
  PUBLIC_API_URL = "https://api.storiesfromtheweb.org/api/v1"

[context.deploy-preview.environment]
  PUBLIC_API_URL = "https://api.storiesfromtheweb.org/api/v1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200