name: Deploy to cPanel via FTPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: FTPS Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: api.storiesfromtheweb.org
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./stories-backend/
        server-dir: /home/stories/api.storiesfromtheweb.org/
        protocol: ftps
        security: loose  # Changed from 'strict' to 'loose' to disable certificate validation